### ISSUE TITLE
Comments cannot be uploaded

### ISSUE THREAD

**Issue by Arcadius2006** [LittleBigRefresh/Refresh#601]
whenever you try to post a comment on a level or profile, it doesn't work

the game spits out a "There was an error posting your comment. Please try again later." error

games tested are: LittleBIgPlanet 2, LittleBIgPlanet 3, LittleBigPlanet PSVita

**Comment by jvyden** [comment]
Looks to be a migration failure:

```
Realms.Exceptions.RealmDuplicatePrimaryKeyValueException: A GameProfileComment object already exists with primary key property SequentialId == '1017'
   at Realms.Realm.AddInternal[T](T obj, Type objectType, Boolean update)
   at Realms.Realm.Add[T](T obj, Boolean update)
   at Refresh.GameServer.Database.GameDatabaseContext.<>c__DisplayClass117_0`1.<AddSequentialObject>b__1() in /home/runner/work/Refresh/Refresh/Refresh.GameServer/Database/GameDatabaseContext.cs:line 102
   at Realms.Realm.Write[T](Func`1 function)
   at Refresh.GameServer.Database.GameDatabaseContext.AddSequentialObject[T](T obj, IList`1 list, Action writtenCallback) in /home/runner/work/Refresh/Refresh/Refresh.GameServer/Database/GameDatabaseContext.cs:line 96
   at Refresh.GameServer.Database.GameDatabaseContext.AddSequentialObject[T](T obj) in /home/runner/work/Refresh/Refresh/Refresh.GameServer/Database/GameDatabaseContext.cs:line 123
   at Refresh.GameServer.Database.GameDatabaseContext.PostCommentToProfile(GameUser profile, GameUser author, String content) in /home/runner/work/Refresh/Refresh/Refresh.GameServer/Database/GameDatabaseContext.Comments.cs:line 23
   at Refresh.GameServer.Endpoints.Game.CommentEndpoints.PostProfileComment(RequestContext context, GameDatabaseContext database, String username, SerializedComment body, GameUser user, IDateTimeProvider timeProvider) in /home/runner/work/Refresh/Refresh/Refresh.GameServer/Endpoints/Game/CommentEndpoints.cs:line 33
   at InvokeStub_CommentEndpoints.PostProfileComment(Object, Span`1)
   at System.Reflection.MethodBaseInvoker.InvokeWithManyArgs(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
```
