### ISSUE TITLE
 'Refresh.GameServer.Configuration.GameServerConfig' does not contain a definition for 'MaximumAssetSafetyLevel'

### ISSUE THREAD

**Issue by R3Skako** [LittleBigRefresh/Refresh#613]
Basically when running the Refresh.Gameserver.exe, this pops up... i'm not sure if it's only on my side, maybe i f'd something up, but i'll leave this here in case if this is actually a bug.
P.S. I did not modify the source code or anything, so there's a 50% chance it's not my fault.
```
[08.04.24 23:06:46] [Info] [Startup] Bunkum is storing its data at C:\Users\RTON\Desktop\Refresh_for_Windows_x64.
[08.04.24 23:06:46] [Info] [Startup] You can override where data is stored using the BUNKUM_DATA_FOLDER environment variable.
[08.04.24 23:06:47] [Info] [Configuration] A new GameServerConfig is being created at C:\Users\RTON\Desktop\Refresh_for_Windows_x64\refreshGameServer.json.
Unhandled exception. Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: 'Refresh.GameServer.Configuration.GameServerConfig' does not contain a definition for 'MaximumAssetSafetyLevel'
   at CallSite.Target(Closure, CallSite, Object)
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Refresh.GameServer.Configuration.GameServerConfig.Migrate(Int32 oldVer, Object oldConfig) in /home/runner/work/Refresh/Refresh/Refresh.GameServer/Configuration/GameServerConfig.cs:line 19
   at System.Dynamic.UpdateDelegates.UpdateAndExecuteVoid3[T0,T1,T2](CallSite site, T0 arg0, T1 arg1, T2 arg2)
   at Bunkum.Core.Configuration.Config.MigrateIfNecessary(String jsonText)
   at Bunkum.Core.Configuration.Config.LoadFromJsonFile[TConfig](String filename, Logger logger)
   at Refresh.GameServer.RefreshGameServer.SetupConfiguration() in /home/runner/work/Refresh/Refresh/Refresh.GameServer/RefreshGameServer.cs:line 101
   at Refresh.Common.RefreshServer.<>c__DisplayClass7_0.<SetupInitializer>b__0(BunkumServer _) in /home/runner/work/Refresh/Refresh/Refresh.Common/RefreshServer.cs:line 37
   at Bunkum.Core.BunkumServer.set_Initialize(Action`1 value)
   at Refresh.Common.RefreshServer.SetupInitializer(Action preServerInitializer) in /home/runner/work/Refresh/Refresh/Refresh.Common/RefreshServer.cs:line 35
   at Refresh.GameServer.RefreshGameServer..ctor(BunkumHttpListener listener, Func`1 databaseProvider, IAuthenticationProvider`1 authProvider, IDataStore dataStore) in /home/runner/work/Refresh/Refresh/Refresh.GameServer/RefreshGameServer.cs:line 63
   at Program.<Main>$(String[] args) in /home/runner/work/Refresh/Refresh/Refresh.GameServer/Startup.cs:line 12
   at Program.<Main>(String[] args)

```

**Comment by Beyley** [comment]
hmmm, definitely a migration bug, you can likely solve it temporarily by downloading a build from a couple versions back, _then_ upgrading to the latest

**Comment by R3Skako** [comment]
Alright, that did the trick, thanks!

**Comment by Beyley** [comment]
still a bug, keeping open until fixed
